--- #YAML:1.0
name:               Net-Spotify
version:            0.03
abstract:           Perl interface to the Spotify Metadata API
author:
    - Edoardo Sabadelli <edoardo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:   0
    Test::More:       0
    URI:              0
    URI::QueryParam:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
